from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import shutil


@dataclass(slots=True)
class ProjectSpec:
    project_name: str
    idea: str
    desired_output: str
    destination: Path
    stakeholders: str = ""
    constraints: str = ""
    tech_stack: str = ""
    no_gos: str = ""
    current_status: str = "kickoff_complete"
    priority: str = "high"
    quality_expectations: str = ""
    success_measures: str = ""
    notes: str = ""


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "agent-project"


def generate_workspace(spec: ProjectSpec, *, force: bool = False) -> Path:
    destination = Path(spec.destination).expanduser().resolve()
    if destination.exists() and any(destination.iterdir()) and not force:
        raise FileExistsError(
            f"Destination '{destination}' already exists and is not empty. "
            "Use --force to write into an existing directory."
        )

    destination.mkdir(parents=True, exist_ok=True)

    template_root = Path(__file__).resolve().parent / "templates" / "workspace"
    shutil.copytree(template_root, destination, dirs_exist_ok=True)

    project_brief_template = destination / "PROJECT" / "zz - PROJECT_BRIEF.md"
    state_template = destination / "STATE" / "zz - run_state.json"

    project_brief_path = destination / "PROJECT" / "PROJECT_BRIEF.md"
    project_context_path = destination / "PROJECT" / "PROJECT_CONTEXT.md"
    architecture_path = destination / "PROJECT" / "ARCHITECTURE.md"
    delivery_plan_path = destination / "PROJECT" / "DELIVERY_PLAN.md"
    decisions_path = destination / "PROJECT" / "DECISIONS.md"
    task_path = destination / "TASKS" / "BACKLOG" / "001-project-kickoff-and-foundation.md"
    state_path = destination / "STATE" / "run_state.json"
    next_action_path = destination / "STATE" / "NEXT_ACTION.md"

    _replace_placeholder(project_brief_template, project_brief_path)
    _replace_placeholder(state_template, state_path)

    _write_text(destination / "README.md", _build_workspace_readme(spec))
    _write_text(project_brief_path, _build_project_brief(spec))
    _write_text(project_context_path, _build_project_context(spec))
    _write_text(architecture_path, _build_architecture(spec))
    _write_text(delivery_plan_path, _build_delivery_plan(spec))
    _write_text(decisions_path, _build_decisions(spec))
    _write_text(task_path, _build_initial_task(spec))
    _write_text(next_action_path, _build_next_action(spec))
    _write_state(state_path, spec)

    for gitkeep_path in (
        destination / "TASKS" / "ACTIVE" / ".gitkeep",
        destination / "TASKS" / "BLOCKED" / ".gitkeep",
        destination / "TASKS" / "DONE" / ".gitkeep",
        destination / "RUNS" / ".gitkeep",
        destination / "REPORTS" / ".gitkeep",
    ):
        gitkeep_path.parent.mkdir(parents=True, exist_ok=True)
        gitkeep_path.touch(exist_ok=True)

    return destination


def _write_text(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _replace_placeholder(placeholder: Path, target: Path) -> None:
    if placeholder.exists():
        placeholder.replace(target)


def _build_workspace_readme(spec: ProjectSpec) -> str:
    generated_on = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"""# {spec.project_name}

This workspace was generated by `agent-builder-template` to support agent-operated delivery for this project.

## Project Summary

- Core idea: {spec.idea}
- Intended output: {spec.desired_output}
- Current status: {spec.current_status}
- Generated on: {generated_on}

## Start Here

- Review `PROJECT/PROJECT_BRIEF.md`
- Review `PROJECT/PROJECT_CONTEXT.md`
- Confirm `PROJECT/ARCHITECTURE.md` and `PROJECT/DELIVERY_PLAN.md`
- Start from `TASKS/BACKLOG/001-project-kickoff-and-foundation.md`
- Keep `STATE/run_state.json` current as the work progresses

## Delivery Flow

`Brief -> Clarify -> Plan -> Architect -> Build -> Critic -> Regression -> Report -> Next Action`

The user should mainly refine the brief and approve important decisions. The agents should carry the structured delivery work forward.
"""


def _build_project_brief(spec: ProjectSpec) -> str:
    stakeholders = spec.stakeholders or "To be defined."
    constraints = spec.constraints or "No explicit constraints were captured at kickoff."
    tech_stack = spec.tech_stack or "Open for decision."
    no_gos = spec.no_gos or "No explicit no-go areas were captured at kickoff."
    success_measures = spec.success_measures or "Success measures still need to be made more concrete."
    notes = spec.notes or "No additional notes were captured at kickoff."

    return f"""# Project Brief

This is the primary source brief for the project. It should stay short, current, and decision-useful.

## Project Name

- Name: {spec.project_name}
- Short description: {spec.idea}

## Core Idea

{spec.idea}

## Intended Output

{spec.desired_output}

## Intended Users Or Stakeholders

{stakeholders}

## Constraints

{constraints}

## Preferred Stack Or Direction

{tech_stack}

## No-Go Areas

{no_gos}

## Success Measures

{success_measures}

## Notes

{notes}
"""


def _build_project_context(spec: ProjectSpec) -> str:
    stakeholders = spec.stakeholders or "To be defined."
    constraints = spec.constraints or "No explicit constraints were captured at kickoff."
    tech_stack = spec.tech_stack or "Open for decision."
    quality_expectations = (
        spec.quality_expectations
        or "Prefer clear, reviewable changes, practical validation, controlled scope growth, and concise documentation."
    )
    success_measures = spec.success_measures or "Concrete success measures still need to be confirmed."
    no_gos = spec.no_gos or "No explicit no-go areas were captured at kickoff."

    return f"""# Project Context

This document translates the short project brief into working context for planning and delivery.

## Project Name

- Name: {spec.project_name}
- Working summary: {spec.idea}

## Project Goal

- Primary objective: Turn the initial brief into a deliverable implementation path.
- Desired outcome: {spec.desired_output}
- Success measures: {success_measures}

## Intended Users Or Stakeholders

- Primary users: {stakeholders}
- Decision-makers: To be defined.
- Other stakeholders: To be defined.

## Current Status

- Stage: {spec.current_status}
- What is already in place: An agent-operated delivery workspace has been generated.
- What is actively being worked on: Converting the kickoff brief into an approved delivery path and first implementation slice.

## Main Constraints

- Time constraints: Not specified yet.
- Budget or resource limits: Not specified yet.
- Compliance, policy, or operational limits: Not specified yet.
- Delivery constraints: {constraints}
- No-go areas: {no_gos}

## Tech Stack

- Languages: {tech_stack}
- Frameworks or libraries: To be decided.
- Data stores or infrastructure: To be decided.
- Key tooling: Agent-operated workflow with intake, planning, architecture, build, review, regression, and reporting stages.

## Architecture Notes

- Major components: To be defined during the architecture pass.
- Important integrations: To be defined after the first delivery decisions.
- Known architectural patterns: Prefer clear boundaries, small interfaces, and simple composition.
- Areas that are sensitive or tightly coupled: Unknown at kickoff.

## Quality Expectations

- Reliability expectations: {quality_expectations}
- Testing expectations: Use targeted checks appropriate to the task size and risk, then increase coverage where shared behavior or regression risk grows.
- Performance expectations: Avoid obvious bottlenecks first; tune once actual usage paths are visible.
- Documentation expectations: Keep brief, context, plan, decisions, state, and reports current enough for handoff.

## Known Risks

- Technical risks: The implementation path may change as architecture and stack decisions become concrete.
- Delivery risks: Scope may expand if the intended output is not kept specific.
- Dependency risks: Tooling and stack choices are still open unless later fixed.

## Out Of Scope

- Explicit exclusions: Anything not required to deliver the intended output.
- Tempting but non-essential work: Premature automation, broad refactoring, speculative features, or provider-specific coupling that is not needed yet.

## Notes For Future Contributors Or Agents

- Preferred working style: Keep changes minimal, clear, and easy to review.
- Important references: Start with the brief, this file, the architecture draft, the delivery plan, and the next action.
- Common pitfalls: Expanding scope before the delivery path is agreed, or implementing before the architecture direction is stable enough.
- Open context gaps to resolve: Architecture boundaries, final stack details, ownership of approvals, and concrete acceptance checks.
"""


def _build_architecture(spec: ProjectSpec) -> str:
    tech_stack = spec.tech_stack or "Open for decision."
    return f"""# Architecture

This is the initial architecture draft created at kickoff. It should guide early work, but it is not beyond revision.

## Architectural Intent

Build **{spec.project_name}** as a clear, maintainable system that can deliver the intended output without unnecessary framework or process overhead.

## Proposed Direction

- Delivery style: Incremental, reviewable slices
- Preferred stack direction: {tech_stack}
- System bias: Start with the simplest structure that can support the intended output
- Integration bias: Add external dependencies only when they materially reduce delivery risk or effort

## Suggested High-Level Shape

- Interface layer: The entry points or surfaces through which users or other systems interact
- Application layer: The main use cases, orchestration logic, and delivery flow
- Domain or rules layer: The business rules or project-specific logic
- Infrastructure layer: Storage, external services, automation, and delivery plumbing

## Early Architectural Principles

- Keep boundaries explicit.
- Keep components small enough to reason about.
- Prefer boring, maintainable choices over novelty.
- Avoid irreversible coupling too early.
- Make testing and review possible without heroic effort.

## Open Decisions

- Final stack and framework choices
- Data model and persistence approach, if required
- Integration points and external services, if required
- Deployment and environment model

## Approval-Sensitive Areas

- Major stack changes after kickoff
- External services with account or cost implications
- Security-sensitive flows
- Destructive data or infrastructure operations
"""


def _build_delivery_plan(spec: ProjectSpec) -> str:
    return f"""# Delivery Plan

This plan translates the kickoff brief into a professional first execution path.

## Delivery Objective

Deliver **{spec.desired_output}** through a sequence of controlled, reviewable steps.

## Phase 1: Clarify And Confirm

- Validate the project brief and constraints
- Confirm no-go areas and expected quality bar
- Identify open decisions that need approval before deeper implementation

## Phase 2: Architecture And Foundation

- Confirm the initial system shape
- Define the smallest useful implementation slice
- Prepare the first backlog items and execution order

## Phase 3: Core Build

- Implement the first meaningful end-to-end path
- Keep changes reviewable and limited to the agreed slice
- Capture tradeoffs and emerging risks as decisions

## Phase 4: Check And Harden

- Run targeted validation against the changed areas
- Review for gaps, overengineering, and side effects
- Tighten obvious weaknesses before widening scope

## Phase 5: Report And Continue

- Summarize what was completed and what remains open
- Update state and next action
- Choose the next delivery slice based on impact and risk

## Immediate Focus

The immediate focus is to turn the kickoff brief into an approved foundation task and then move into the first build slice with as little ambiguity as possible.
"""


def _build_decisions(spec: ProjectSpec) -> str:
    tech_stack = spec.tech_stack or "Pending decision"
    return f"""# Decisions

Use this file to record decisions that materially shape the project.

## Initial Decisions

- The project will be delivered through an agent-operated workflow rather than an unstructured prompt chain.
- The work should proceed in reviewable slices instead of broad, one-pass implementation.
- The current preferred stack direction is: {tech_stack}

## Pending Decisions

- Final architecture boundaries
- Final stack and framework choices
- Any external services or paid tooling
- Deployment and environment strategy

## Decision Rules

- Record the decision, why it was made, and what it affects.
- Escalate decisions that change cost, security posture, architecture, or delivery risk.
- Prefer reversible decisions early and stronger commitments once evidence improves.
"""


def _build_initial_task(spec: ProjectSpec) -> str:
    constraints = spec.constraints or "Keep the first version practical and proportional."
    no_gos = spec.no_gos or "No explicit no-go areas were defined yet."
    notes = spec.notes or "No additional notes."
    return f"""# Project Kickoff And Foundation

## Request

Turn the kickoff material for **{spec.project_name}** into an approved, executable first delivery slice.

- Core idea: {spec.idea}
- Intended output: {spec.desired_output}

## Why This Matters

This task converts a rough idea into a controlled delivery path. It is the bridge between intake and serious implementation work.

## Constraints

- Time or deadline constraints: Not specified yet.
- Technical constraints: {constraints}
- Process or approval constraints: Not specified yet.
- No-go areas: {no_gos}

## Priority

{spec.priority}

## Definition Of Done

- The kickoff brief has been checked for gaps or conflicts.
- The architecture direction is stable enough for the first build slice.
- The first executable implementation slice is defined clearly.
- Important risks, approvals, and open decisions are captured.
- The next task can be moved into `TASKS/ACTIVE` without ambiguity.

## Relevant Files Or Context

- `PROJECT/PROJECT_BRIEF.md`
- `PROJECT/PROJECT_CONTEXT.md`
- `PROJECT/ARCHITECTURE.md`
- `PROJECT/DELIVERY_PLAN.md`
- `PROJECT/DECISIONS.md`
- `SYSTEM/QUALITY_BAR.md`
- `SYSTEM/APPROVAL_GATES.md`
- `AGENTS.md`
- `AGENTS/`

## Risks Or Cautions

- Requirements may still shift as more details become explicit.
- Architecture or stack decisions may need revision if the brief is still underspecified.
- Scope can grow quickly if the intended output is not kept concrete.
- Premature implementation can create avoidable rework if approval-sensitive decisions are skipped.

## Notes

{notes}
"""


def _build_next_action(spec: ProjectSpec) -> str:
    return f"""# Next Action

## Recommended Next Step

Review the kickoff artifacts for **{spec.project_name}**, confirm any missing constraints or no-go areas, and then refine `TASKS/BACKLOG/001-project-kickoff-and-foundation.md` into the first active execution task.

## Owner

Planner and Architect roles, with user approval where required.

## Why This Is Next

The project already has a delivery workspace. The remaining gap is to confirm the first execution slice before implementation begins.
"""


def _write_state(path: Path, spec: ProjectSpec) -> None:
    run_id = f"kickoff-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}-001"
    risks = [
        "Requirements may evolve as the project context becomes more specific."
    ]
    if not spec.tech_stack:
        risks.append("The technical stack is still open and may affect implementation choices.")
    if spec.constraints:
        risks.append(f"Constraint to watch: {spec.constraints}")
    if spec.no_gos:
        risks.append(f"No-go area to respect: {spec.no_gos}")

    payload = {
        "project_name": spec.project_name,
        "last_run_id": run_id,
        "current_status": spec.current_status,
        "current_phase": "kickoff",
        "active_task": None,
        "backlog_count": 1,
        "blocked_count": 0,
        "completed_count": 0,
        "open_issues": [],
        "known_risks": risks,
        "approval_gates_pending": [
            "final architecture confirmation",
            "stack confirmation" if not spec.tech_stack else "stack validation against real delivery needs",
        ],
        "last_updated": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
