from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import shutil


@dataclass(slots=True)
class ProjectSpec:
    project_name: str
    idea: str
    desired_output: str
    destination: Path
    stakeholders: str = ""
    constraints: str = ""
    tech_stack: str = ""
    current_status: str = "intake"
    priority: str = "high"
    quality_expectations: str = ""
    notes: str = ""


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "agent-project"


def generate_workspace(spec: ProjectSpec, *, force: bool = False) -> Path:
    destination = Path(spec.destination).expanduser().resolve()
    if destination.exists() and any(destination.iterdir()) and not force:
        raise FileExistsError(
            f"Destination '{destination}' already exists and is not empty. "
            "Use --force to write into an existing directory."
        )

    destination.mkdir(parents=True, exist_ok=True)

    template_root = Path(__file__).resolve().parent / "templates" / "workspace"
    shutil.copytree(template_root, destination, dirs_exist_ok=True)

    project_context_template = destination / "PROJECT" / "zz - PROJECT_CONTEXT.md"
    task_template = destination / "TASKS" / "zz - TASK_BRIEF_TEMPLATE.md"
    state_template = destination / "STATE" / "zz - run_state.json"

    project_context_path = destination / "PROJECT" / "PROJECT_CONTEXT.md"
    task_path = destination / "TASKS" / "INITIAL_BUILD_TASK.md"
    state_path = destination / "STATE" / "run_state.json"

    if project_context_template.exists():
        project_context_template.rename(project_context_path)
    if task_template.exists():
        task_template.rename(task_path)
    if state_template.exists():
        state_template.rename(state_path)

    _write_text(destination / "README.md", _build_workspace_readme(spec))
    _write_text(project_context_path, _build_project_context(spec))
    _write_text(task_path, _build_initial_task(spec))
    _write_text(destination / "AGENTS.md", _rewrite_agents_overview(destination / "AGENTS.md"))
    _write_state(state_path, spec)

    for gitkeep_path in (
        destination / "RUNS" / ".gitkeep",
        destination / "REPORTS" / ".gitkeep",
    ):
        gitkeep_path.parent.mkdir(parents=True, exist_ok=True)
        gitkeep_path.touch(exist_ok=True)

    return destination


def _write_text(path: Path, content: str) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _rewrite_agents_overview(path: Path) -> str:
    content = path.read_text(encoding="utf-8")
    return content.replace("PROJECT/zz - PROJECT_CONTEXT.md", "PROJECT/PROJECT_CONTEXT.md")


def _build_workspace_readme(spec: ProjectSpec) -> str:
    generated_on = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"""# {spec.project_name}

This workspace was generated by `agent-builder-template` to support AI-assisted development for this project.

## Project Summary

- Core idea: {spec.idea}
- Intended output: {spec.desired_output}
- Current status: {spec.current_status}
- Generated on: {generated_on}

## Start Here

- Review `PROJECT/PROJECT_CONTEXT.md`
- Start from `TASKS/INITIAL_BUILD_TASK.md`
- Keep `STATE/run_state.json` current as the work progresses

## Operating Flow

`Request -> Plan -> Build -> Check -> Report`

Use the fast path for small, clear tasks and the full path for work with more uncertainty, scope, or risk.
"""


def _build_project_context(spec: ProjectSpec) -> str:
    stakeholders = spec.stakeholders or "To be defined."
    constraints = spec.constraints or "No explicit constraints were captured at intake."
    tech_stack = spec.tech_stack or "Open for decision."
    quality_expectations = (
        spec.quality_expectations
        or "Prefer clear, reviewable changes, practical validation, and concise documentation."
    )
    notes = spec.notes or "No additional notes were captured at intake."

    return f"""# Project Context

This document was generated from the initial project intake. Update it as the project becomes more concrete.

## Project Name

- Name: {spec.project_name}
- Short description: {spec.idea}

## Project Goal

- Primary objective: Turn the initial idea into a workable project with a clear delivery path.
- Desired outcome: {spec.desired_output}
- What success looks like: The project produces the intended output in a way that is understandable, maintainable, and reviewable.

## Intended Users Or Stakeholders

- Primary users: {stakeholders}
- Decision-makers: To be defined.
- Other stakeholders: To be defined.

## Current Status

- Stage: {spec.current_status}
- What is already in place: An initial agent-ready workspace has been generated.
- What is actively being worked on: Defining and executing the first implementation pass.

## Main Constraints

- Time constraints: Not specified yet.
- Budget or resource limits: Not specified yet.
- Compliance, policy, or operational limits: Not specified yet.
- Delivery constraints: {constraints}

## Tech Stack

- Languages: {tech_stack}
- Frameworks or libraries: To be decided.
- Data stores or infrastructure: To be decided.
- Key tooling: Agent-assisted development workflow with structured planning, build, and review stages.

## Architecture Notes

- Major components: To be defined during planning.
- Important integrations: To be defined during planning.
- Known architectural patterns: Prefer simple structure before specialized abstractions.
- Areas that are sensitive or tightly coupled: Unknown at intake.

## Quality Expectations

- Reliability expectations: {quality_expectations}
- Testing expectations: Use targeted checks appropriate to the task size and risk.
- Performance expectations: Avoid obvious bottlenecks; tune later when real needs are visible.
- Documentation expectations: Keep context and outcomes current enough for handoff.

## Known Risks

- Technical risks: The best implementation path may change as discovery progresses.
- Delivery risks: Scope may expand if the intended output is not kept specific.
- Dependency risks: Tooling and stack choices are still open unless later fixed.

## Out Of Scope

- Explicit exclusions: Anything not required to deliver the intended output.
- Tempting but non-essential work: Premature automation, broad refactoring, or speculative features.

## Notes For Future Contributors Or Agents

- Preferred working style: Keep changes minimal, clear, and easy to review.
- Important references: Start with this file, `AGENTS.md`, and the initial task brief.
- Common pitfalls: Expanding scope before the core output is defined well enough.
- Open context gaps to resolve: Architecture, final stack details, and concrete acceptance checks.

## Intake Notes

{notes}
"""


def _build_initial_task(spec: ProjectSpec) -> str:
    constraints = spec.constraints or "Keep the first version practical and proportional."
    notes = spec.notes or "No additional notes."
    return f"""# Initial Build Task

## Request

Create the first working version of **{spec.project_name}** based on the project brief below.

- Core idea: {spec.idea}
- Intended output: {spec.desired_output}

## Why This Matters

This task establishes the first concrete implementation path and turns the intake brief into executable work.

## Constraints

- Time or deadline constraints: Not specified yet.
- Technical constraints: {constraints}
- Process or approval constraints: Not specified yet.

## Priority

{spec.priority}

## Definition Of Done

- The project has a clear first implementation pass.
- The result is aligned with the stated intended output.
- The work remains understandable, reviewable, and easy to continue.
- Any important risks or open points are captured clearly.

## Relevant Files Or Context

- `PROJECT/PROJECT_CONTEXT.md`
- `AGENTS.md`
- `AGENTS/`

## Risks Or Cautions

- Requirements may still shift as more details become explicit.
- Stack or architecture decisions may need revision once implementation starts.
- Scope can grow quickly if the intended output is not kept concrete.

## Notes

{notes}
"""


def _write_state(path: Path, spec: ProjectSpec) -> None:
    run_id = f"run-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}-001"
    risks = [
        "Requirements may evolve as the project context becomes more specific."
    ]
    if not spec.tech_stack:
        risks.append("The technical stack is still open and may affect implementation choices.")
    if spec.constraints:
        risks.append(f"Constraint to watch: {spec.constraints}")

    payload = {
        "project_name": spec.project_name,
        "last_run_id": run_id,
        "current_status": spec.current_status,
        "open_issues": [],
        "known_risks": risks,
        "last_updated": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
